# Generated by Django 3.1.1 on 2020-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPemilih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nik', models.CharField(max_length=17)),
                ('nim', models.CharField(max_length=11)),
                ('tanggal_lahir', models.DateField()),
                ('angkatan', models.CharField(max_length=5)),
                ('password', models.CharField(editable=False, max_length=6)),
            ],
        ),
    ]
