# Generated by Django 3.1.1 on 2020-11-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapemilih',
            name='nik',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='datapemilih',
            name='nim',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
