# Generated by Django 3.1.1 on 2020-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0002_auto_20201118_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapemilih',
            name='password',
            field=models.CharField(max_length=6),
        ),
    ]
